name: Build recovery(twrp,shrp,pbrp)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Init the System
         uses: actions/checkout@master
         
       - name: Adding and Sync source
         run: |
             source config.sh
             mkdir work
             cd work
             repo init -u $MANIFEST -b $BRANCH --depth=1
             repo sync -c -j`nproc` --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK -b $DT_BRANCH device/$VENDOR/$DEVICE
       - name: Build recovery
         run: |
              source config.sh
              cd work
              . build/envsetup.sh && lunch $TYPE$SYM$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET -j`nproc`
       - name: Making file
         run: |
              source config.sh
              cd work
              wget -qO - https://github.com/SA-17/Recovery_builder/raw/main/scripts/bake.sh  | bash
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: recovery image
          files: work/recovery.zip
