name: Compilar TWRP

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Compilación de TWRP
    runs-on: ubuntu-latest
    
    steps:
    - name: Configurar ambiente
      run: |
        sudo apt update
        sudo apt install -y git python3 python-is-python3 android-tools-adb android-tools-fastboot
        
    - name: Clonar repositorio TWRP
      run: |
        git clone https://github.com/TeamWin/Team-Win-Recovery-Project.git twrp
        cd twrp
        git submodule init
        git submodule update
        
    - name: Configurar el dispositivo
      run: |
        cd twrp
        git clone https://android.googlesource.com/platform/build
        git clone https://github.com/twrpdtgen/android_device_samsung_a03s
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_a03s-eng
        
    - name: Compilar TWRP
      run: |
        cd twrp
        mka recoveryimage
        
    - name: Subir archivo TWRP
      uses: actions/upload-artifact@v2
      with:
        name: twrp-recovery
        path: twrp/out/target/product/a03s/recovery.img
